#!/usr/bin/env bash
# Android Studio workspace setup for the MONEYTEAM / NexusPipe Android client.
# Creates the workspace skeleton, a debug/release keystore strategy backed by
# AndroidKeyStore, and prints honest verification for each step.
set -euo pipefail

WORKSPACE="${1:-./android-workspace}"
KEYSTORE_FILE="${KEYSTORE_FILE:-${WORKSPACE}/keystore/release.keystore}"
KEYSTORE_PASS="${KEYSTORE_PASS:?Set KEYSTORE_PASS before running (never commit it)}"

echo "== Setting up Android workspace at ${WORKSPACE} =="

# 1. AndroidKeyStore helper is already packaged at:
#    android/app/src/main/java/com/moneyteam/nexuspipe/security/KeystoreHelper.java
mkdir -p "${WORKSPACE}"

# 2. Java toolchain check
if ! command -v java >/dev/null 2>&1; then
  echo "MISSING: java not found. Install Android Studio (https://developer.android.com/studio) first." >&2
  exit 1
fi
echo "Java: $(java -version 2>&1 | head -1)"

# 3. Debug keystore (auto-generated by Gradle on first build) — verify AndroidKeyStore works:
if command -v keytool >/dev/null 2>&1; then
  mkdir -p "$(dirname "${KEYSTORE_FILE}")"
  keytool -genkeypair -v \
    -keystore "${KEYSTORE_FILE}" \
    -alias nexuspipe-release \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass "${KEYSTORE_PASS}" \
    -dname "CN=NexusPipe, OU=Mobile, O=MONEYTEAM, C=US"
  echo "RELEASE_KEYSTORE_CREATED: ${KEYSTORE_FILE}"
  echo "Add to ~/.gradle/gradle.properties (never commit):"
  echo "  NEXUSPIPE_STORE_FILE=${KEYSTORE_FILE}"
  echo "  NEXUSPIPE_STORE_PASSWORD=***"
  echo "  NEXUSPIPE_KEY_ALIAS=nexuspipe-release"
  echo "  NEXUSPIPE_KEY_PASSWORD=***"
else
  echo "keytool not found — skipping release keystore generation." >&2
fi

# 4. Hardware-backed keys note
cat << 'EOF'
AndroidKeyStore notes (hardware-backed, no file):
- Keys generated inside AndroidKeyStore never leave secure hardware.
- KeystoreHelper.java (packaged in this repo) reads the certificate chain:
    KeyStore keyStore = KeyStore.getInstance("AndroidKeyStore");
    keyStore.load(null);
    Certificate cert = keyStore.getCertificate(alias);
    PublicKey publicKey = cert.getPublicKey();
- Sign debug builds with the auto debug keystore; sign release builds via
  Play App Signing or the release keystore created above.
EOF

echo "WORKSPACE_SETUP_DONE"
